In [1]:
import pandas as pd
import numpy as np

data_set = pd.read_csv('airbnb_lisbon_1480_2017-07-27.csv')
data_set.head()

data_set2 = data_set.apply(lambda x: x.astype(str).str.lower()) #this converts dataframe to lowercase
col_to_drop = ["country", "borough", "room_id", "survey_id", "host_id", "bathrooms", "minstay", "last_modified","latitude","longitude","location"]
my_data = data_set2.drop(col_to_drop, axis=1)
my_data[['reviews','overall_satisfaction','price']] = my_data[['reviews','overall_satisfaction','price']].astype('float')
#my_data.dtypes


#dropped_col_data = dropped_col_data[dropped_col_data.reviews !=0]
new_data = my_data[my_data["reviews"] != 0]

new_data.tail(20)
new_data.to_csv('cleaned_data.csv', index=False)

In [2]:
# What is the relationship between neighbourhood and room type?
# Count number of room types per neighbourhood 

room_type = pd.get_dummies(new_data['room_type'])

In [3]:
new_data = pd.concat([new_data, room_type], axis=1)
sorted_data = new_data.sort_values(by=['neighborhood'])
sorted_data.head()

,room_type,city,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price,name,entire home/apt,private room,shared room
4738,entire home/apt,lisbon,ajuda,16.0,4.5,6,2.0,77.0,lisbon memory apartment,1,0,0
5087,entire home/apt,lisbon,ajuda,8.0,5.0,5,2.0,71.0,cosy apartment with view near belém,1,0,0
5096,entire home/apt,lisbon,ajuda,12.0,4.5,6,3.0,66.0,*terrace flat ajuda/belem lisbon -,1,0,0
5100,entire home/apt,lisbon,ajuda,20.0,4.5,6,2.0,82.0,new! belém bright 2 bedroom apartment - free wifi,1,0,0
5104,entire home/apt,lisbon,ajuda,15.0,5.0,4,2.0,81.0,river view apartment with balconies near belem,1,0,0

In [4]:
final_data = sorted_data.groupby('neighborhood').mean()
col_to_drop2 = ["reviews", "overall_satisfaction", "price"]
final_data = final_data.drop(col_to_drop2, axis=1)

In [5]:
#final_data.head(30)
#final_data.sort_values('entire home/apt')
#final_data.to_csv('luke_final_data.csv')

In [9]:
most_entire_home = final_data.sort_values(by=['entire home/apt'], ascending=False)
most_entire_home['entire home/apt'] = pd.Series(["{0:.2f}%".format(val * 100) 
                                                for val in most_entire_home['entire home/apt']], 
                                                index = most_entire_home.index)
most_entire_home['private room'] = pd.Series(["{0:.2f}%".format(val * 100) 
                                                for val in most_entire_home['private room']], 
                                                index = most_entire_home.index)
most_entire_home['shared room'] = pd.Series(["{0:.2f}%".format(val * 100) 
                                                for val in most_entire_home['shared room']], 
                                                index = most_entire_home.index)

most_entire_home.head()

                  entire home/apt private room shared room
neighborhood
carnide                    91.30%        8.70%       0.00%
parque das nações          88.65%       10.27%       1.08%
misericórdia               87.65%       11.65%       0.70%
santa maria maior          87.46%       11.71%       0.83%
são vicente                87.27%       12.19%       0.54%

In [7]:
most_private_room = final_data.sort_values(by=['private room'], ascending=False)
most_entire_home['entire home/apt'] = pd.Series(["{0:.2f}%".format(val * 100) 
                                                for val in most_entire_home['entire home/apt']], 
                                                index = most_entire_home.index)
most_entire_home['private room'] = pd.Series(["{0:.2f}%".format(val * 100) 
                                                for val in most_entire_home['private room']], 
                                                index = most_entire_home.index)
most_entire_home['shared room'] = pd.Series(["{0:.2f}%".format(val * 100) 
                                                for val in most_entire_home['shared room']], 
                                                index = most_entire_home.index)

most_private_room.head(10)

ValueError: Unknown format code 'f' for object of type 'str'

In [ ]:
most_shared_room = final_data.sort_values(by=['shared room'], ascending=False)
most_shared_room.head(10)